---
- hosts: all
  become: true

  tasks:
    - name: Execute hostname
      shell: hostname
      register: output

    - debug:
        var: output.stdout

    - name: Execute date
      shell: date
      register: datestr

    - debug:
        var: datestr.stdout
