---
- hosts: all
  become: true

  tasks:

  - name: Execute hostname
    shell: hostname
    register: output

  - debug:
    var: output.stdout
  # Normally We set hostname with the following command:
  #   # hostnaemctl set-hostname your-new-hostname
  # Ansible has a module for that though
  # The variable "hostname" will need to be defined to run this
  - name: Set your hostname
    hostname: 
      name: "{{ hostname }}"
    
  - name: Display your hostname
    command: hostname
    register: output

  - debug:
    var: output.stdout

    