---

environment: 
  http_proxy: http://internetproxy.courts.judiciary.state.nj.us:8080/
  https_proxy: http://internetproxy.courts.judiciary.state.nj.us:8080/
  
- src: geerlingguy.logstash
  
- src: geerlingguy.elasticsearch

- src: geerlingguy.kibana